### ISSUE TITLE
Light problem

### ISSUE THREAD

**Issue by AlexDBn1** [baileymh/statblock-library#14]
Hi, I've been using your module on pathfider for a while now, but I've run into a problem where, when I place an imported monster and a light source on the same map, the token and map stop working properly for me (some players don't have this issue for some reason) until I remove the light or the token, plus the monster's token's bright vision can't have any value.

**Comment by baileymh** [comment]
Unfortunately, that would be an issue with the statblock converter module (https://github.com/Lavaeolous/PF1-StatBlock-Converter-Module), likely a result of it not being updated with the recent changes to pf's lighting/vision. 

My module is just the statblock text, and sends it to sbc, so any issues with the produced token are unfortunately out of my control. Sorry I can't be of more help.

It's possible you have a mod conflict or something, if you've updated recently (I'm a little behind on updates)? Might try disabling some of your modules and see if that makes a difference.
