### ISSUE TITLE
Import button broken?

### ISSUE THREAD

**Issue by Tobyn52** [baileymh/statblock-library#17]
I've run into a curious problem where I can't use the button to import a statblock using SBC.  Manually copying the data works fine, and when I edit the imported statblock journal entry, the button seems to be an empty link. That said, I don't have the slightest clue if that's normal.

If there's any other info I can provide, I'd be more than happy to.

EDIT: I'll also mention that this behavior occurred with all modules deactivated except SBC and Statblock Library.

**Comment by baileymh** [comment]
Hmm. So far as I know there are no other issues. 

It's worth noting the journal entries aren't intended to be edited. Any editing that might be needed should be done at import. 

The only thing I can suggest is to uninstall and reinstall the library module. I know the last update I mistakenly included some code I shouldn't have that caused issues, but it was quickly fixed. Perhaps you have some of that? So, try reinstalling and see if that fixes it, and let me know.

**Comment by Tobyn52** [comment]
Finally got a chance to get back to my game and do some prep. I tried reinstalling the Statblock Library, but sadly the problem persists. It doesn't seem to be all people, based on the 1 or 2 comments I've seen on the Foundry Discord.

I can manually import, so really it's just a loss of some convenience.

**Comment by baileymh** [comment]
Yea, I've only seen one comment so far, which I assumed was yours about it. Try opening a new/different world and testing it again?

**Comment by Basqueeroni** [comment]
I am running into this issue as well in Forge. 

I spoke to Primer on Disord, and he said that the library needs to be updated on Forge for the import button to work.  The latest version on forge is 0.2.4, and here was 0.2.5.

I tried a manual installation, but the manifest url gave me version 0.2.0

**Comment by baileymh** [comment]
Hmmm.... I don't really interact too much with Forge. 

I've tried to remove the 0.2.4 version, and have updated to 0.2.6. I don't know how long it takes to propagate an update to Forge, but once it does, let me know if that fixes the issue for you.

**Comment by Basqueeroni** [comment]
As of now, it does not appear as an option to update in the forge Module Bazaar.  I will keep an eye out for it.

In the meantime is there a way to get the manifest link to install the latest version instead of 0.2.0.  I am not sure if that's changeable.

Thanks!

**Comment by Basqueeroni** [comment]
The 0.2.5 update is now live and SBC import is working again.  Thank you.
