### ISSUE TITLE
Reach overwitten by stature.

### ISSUE THREAD

**Issue by JAdams0** [baileymh/statblock-library#4]
When a monster is imported the reach is correct but it is almost immediately overwritten by stature if they do not match. As an example dire bat has 5 foot reach but is imported as tall instead of long, which immediately sets the reach to 10 feet if you close/open the token or actor.  If possible try to import the correct stature for the monsters or set each attack to x feet instead of melee based on reach.

**Comment by baileymh** [comment]
Hi JSams0, so this would be a problem with sbc. My module just provides  the statblocks, and allows for a quick insert into sbc, but the actual importing is all handled by sbc. 

You'll want to look here: https://github.com/Lavaeolous/PF1-StatBlock-Converter-Module

**Comment by JAdams0** [comment]
OH sorry, I actually meant to put it on the converter must have just accidently opened the github for this module.
