### ISSUE TITLE
Recent Update to Pathfinder 1e or possibly Foundry itself breaks this

### ISSUE THREAD

**Issue by NeutralGoodGamer** [baileymh/statblock-library#5]
Not sure which update it was but after updating I cant get this to work (worked fine before), once added the world refuses to load even with this being the ONLY module installed and being left for hours to load (removing this module fixes it) which is a HUGE shame because prepping/running a Pathfinder module on Foundry is a million times easier with the monsters, etc. pre-loaded from your library is so awesome so i hope this can be resolved :D

**Comment by NeutralGoodGamer** [comment]
Oh and I THINK these are the versions i'm using (sorry new to foundry, long time roll20 user though)

Pathfinder 1e - 0.80.9
Foundry VTT - 9.249

The both have something similar to a USB symbol before them

**Comment by baileymh** [comment]
@NeutralGoodGamer 
Hmm. I think your PF 1e is quite a bit outdated, the latest version is 0.80.9 I think, maybe .8. 

Try updating that and let me know, so far I've not heard issues from other people, and with the amount of people who use this, it likely should have come up if it's wide spread. 

Additionally, after you update you pf system, hit F12 and check for errors as you try to load.

**Comment by NeutralGoodGamer** [comment]
oops that was actually a typo error 0.80.9 is what is already sorry

**Comment by NeutralGoodGamer** [comment]
Testing again to be sure and to F12 so far i got a yellow ! that says compatibility risk, last verified 9.242, also statblock library is version 0.1.8

**Comment by NeutralGoodGamer** [comment]
error stuff, deleted for privacy

**Comment by baileymh** [comment]
None of that seems related to my module. 
Are you self-hosting or running from Forge?
If you are using forge, how much ram does it have?

**Comment by NeutralGoodGamer** [comment]
it only gets the errors when your module is installed, im using Amazon web service

**Comment by NeutralGoodGamer** [comment]
Your module was working fine before i updated Pathfinder and Foundry

**Comment by baileymh** [comment]
I have no experience with Amazon web service. From my own testing and asking in the discord, no one else has gotten any issues, so I think the problem is somehow on your side or at least not directly related to my module.

It looks like its something related to the dns you are using. Perhaps try using Google's or something else for your DNS and see if that resolves it. Otherwise, the only real suggestion I can give it to seek help in the Foundry discord server, potentially Module Troubleshooting.

**Comment by NeutralGoodGamer** [comment]
thanks for trying to help :)
