### ISSUE TITLE
Foundry Server Debug Log shows warning...

### ISSUE THREAD

**Issue by karpana** [baileymh/statblock-library#6]
When I restart my Foundry instance, this message is continually present in the `debug.log` file.

Foundry Version: v9 build 249
System: PF1
Host/Server Operating System: Raspberry Pi 4.

```
{"level":"warn","message":"Package statblock-library contains 36 compendium definitions that still use the deprecated 'entity' field instead of 'type'.","timestamp":"2022-02-07 09:18:05"}
```

**Comment by baileymh** [comment]
I haven't updated the module to 9.249 just yet, an update will be posted soon that should take care of it.

**Comment by karpana** [comment]
Sounds wonderful. 
It's not a 'breaking' issue. But compatibility as the platform moves forward is important.
