### ISSUE TITLE
Manifest URL on foundryvtt.com is broken

### ISSUE THREAD

**Issue by DrMcCoy** [baileymh/statblock-library#8]
The Manifest URL at https://foundryvtt.com/packages/statblock-library links to
`https://github.com/baileymh/statblock-library/releases/latest//module.json`
instead of either
`https://github.com/baileymh/statblock-library/releases/latest/download/module.json`
or
`https://github.com/baileymh/statblock-library/releases/download/0.2.1/module.json`

This breaks installing/updating statblock-library via the setup within Foundry VTT.

**Comment by baileymh** [comment]
Thanks. Fixed.
